project:
  type: website
  output-dir: docs
  pre-render:
    - pkgs.r
  render:
    - "*.qmd"
    - "!*.ipynb"
website:
  title: Stats 6257 Fall 2023 - Support Vector Machines
  navbar:
    right:
      - text: "Home"
        file: index.qmd
      - text: "Presentation"
        file: slides.qmd
      - text: "Journal Entries"
        menu:
          - text: "Brad's Journal"
            file: Journal/brad.qmd
          - text: "Eric's Journal"
            file: Journal/eric.qmd
          - text: "Josh's Journal"
            file: Journal/josh.qmd
      - text: "About"
        file: about.qmd
      - text: "Data Reports"
        file: MIMIC_ICU_Data/dataMaid_data.Rmd
format:
  html:
    theme: solar
    toc: true