---
title: "SVM application in Data Mining in EMR"
author: "Brad Lipson"
date: '`r Sys.Date()`'
format:
  html:
    code-fold: true
course: STA 6257 - Advanced Statistical Modeling
bibliography: ../references.bib # file contains bibtex for references
#always_allow_html: true # this allows to get PDF with HTML features
self-contained: true
execute: 
  warning: false
  message: false
editor: 
  markdown: 
    wrap: 72
---

## Summary of Articles

Support vector machines (SVMs) are a powerful method for machine
learning that can be used for data mining. There are several different
SVM kernels, and it is not always clear which one is best for a certain
job. The goal of this paper is to help data scientists pick the best SVM
kernel for a given job. The authors looked at how well different SVM
models did at classification, regression, and clustering, among other
data mining tasks. They used both real-world data and data that they
made up themselves. The article by Xu et al. aimed to see how well
various SVM kernels did at data mining jobs. They found that SVM with
the RBF kernel did the best job at most data mining tasks. However, they
also found that the performance of the different SVM kernels relies on
the task and data set. One problem with this study is that there were
only a few data mining jobs carried out. **(5)**

My next journal suggested a new SVM algorithm for jobs related to data
mining. This is important since SVM is a powerful machine learning
method, but they can be hard to train, especially on big datasets. The
goal of this study is to suggest a new SVM algorithm that works better
for data mining. They came up with a new SV algorithm that is made for
data mining jobs. The program uses several methods to improve how well
SVM training works. They tested how well their new SVM algorithm did at
classification, regression, and grouping, among other tasks in data
mining. They found that their new SVM algorithm was better at most data
mining jobs than other SVM algorithms. But this algorithm has a weakness
in that it is harder to understand than other SVM algorithms. **(3)**

In addition, Zhou et al wrote about deep mining of electronic medical
data using support vector machines to predict the prognosis of severe,
acute myocardial infarction. The authors talked about how the MIMIC-3
database is used to find the 13 markers for heart attack cases. They
compared SVM algorithms and found that the model was about 92% accurate.
They use this model to pull out certain features from the EMR and
identify which patients will have a MI. They said that this helps
doctors figure out the classification regression parts of a disease
outlook. **(6)**

My next piece was about how Fouodo et al and others used support vector
machines for survival analysis with R. They used the survivalSVM package
to do three different kinds of survival analysis. They used both
regression and ranking, which is a mix of the two. The next way to find
the constraints was to use regression followed by Cox proportional
hazard models. They stated that the SVM worked about as well as other
methods on the datasets they used. So, this R package makes it quick and
easy to find out how likely a patient is to live. **(2)**

Another article was called "Using Support Vector Machines for Diabetes
Mellitus Classification from Electronic Medical Records." The goal of
this work is to show how support vector machines (SVMs) in electronic
medical records (EMRs) can be used to classify diabetes mellitus. This
study looked at how well SVMs can classify diabetes because they have
been good at diagnosing other diseases from electronic medical records
(EMRs). The writers used EMRs from both people with and without diabetes
to train an SVM model. During preparation, noise and outliers were first
taken out of the EMRs. The SVM model was then trained with the help of
guided learning. **(1)**

The next journal discussed a way to predict hospital readmissions using
support vector machines. The goal of this study is to make a support
vector machine (SVM) model that can predict a patient's return to the
hospital. The importance was that going back to the hospital is a deadly
problem in health care, and it can be expensive for patients. A reliable
predictor of hospital readmission could help hospitals find people who
are at risk and give them treatment to keep them from going back to the
hospital. A solution is that a collection of electronic medical records
(EMRs) was used to train an SVM model. First, during preprocessing,
abnormalities were taken out of the EMRs. The SVM model was then trained
with the help of guided learning and separated the information into two
groups. With the SVM model, this included readmitted patients who had to
go back to the hospital. **(4)**

SVM was used by Vieira et al. to divide data into two groups. The
algorithm maps the raw data to a high-dimensional feature space, where a
linear classification surface is made. The SVM method then tries to find
the best hyperplane that separates the two types of data by the most.
The margin is the distance between the hyperplane and the data points in
each group that are closest to the hyperplane. The SVM algorithm also
uses a kernel function to move the raw data into a space with more
dimensions, where it is easier to separate. The kernel function is a
piece of math that figures out how similar two data points are to each
other. SVM also uses regularization to control the trade-off between
making the margin as big as possible and making the classification
mistake as small as possible. The SVM algorithm learns from a set of
labeled data, where each data point has a label that tells what group it
belongs to. Once the SVM algorithm has been taught, it can be used to
put new data points that have not been labeled into one of the two
groups. **(7)**

Yang et al. evaluated the performance a version of GAN called
conditional medical GAN (C-med GAN) could determine who would die among
ICU patients. The study used data from the Medical Information Mart for
Intensive Care III (MIMIC-III) database and compared the success of the
C-med GAN with some baseline models, such as the simplified acute
physiology score II (SAPS II), the support vector machine (SVM), and the
multilayer perceptron (MLP). The dataset was split into three sizes, and
a 5-fold grid search cross-validation process was used to find the best
hyperparameters and then the best model selection for the C-med GAN.
Area under the precision-recall curve (PR-AUC), area under the receiver
operating characteristic curve (ROC-AUC), and F1 score were used to
measure the C-med GAN's accuracy. The study came up with a helpful
method to use SAPS II results to directly estimate how long a patient
will live. The results of this study could be used in intensive care to
make it easier to predict mortality in the ICU. **(8)**

The next article was about SVM and classifying cancer diagnosis using
decision support. Chandrashekar et al compared SVM to KNN, RF, bayes and
a decision tree to see which algorithm was better at classifying cancer
in patients. They pulled from 20 cancer databased and tried to recognize
the pattern from genetic variants.  They came up with a preliminary
model after much data cleanup and feature selection with 5 out of the 88
possible features.  They improved the model with the use of 16 important
features and divided up to two model groups.  The authors trained on 20
datasets with one and just 15 with the other but still have 5 dataset to
test from. The F1 score was 0.17 for the SVM model and 0.11, 0.34 for
recall.  So, overall SVM has about 88% accuracy, which was better than
the other ML algorithms and best performance overall. **(9)**

Mandakini et al used SVM to predict Heart and Liver disease, but they
added Swarm Optimization alongside it.  They took their data from the
UCI machine learning repository and then looked at the accuracy, error
and recall of the model.  The authors stated that the SVM was a better
classifier for predicting liver disorders and cardiac arrythmias.  They
first normalized the dataset then trained it and constructed a SVM mode,
then added a data structure.  Later, they optimized the SVM model using
the Crazy Particle Swarm Optimization (CPSO).  Then they added a Cauchy
mutation and constructed their model.  Finally, they could test and
classify their data with an F1 score of 89.55 for just SVM on heart
disease and 77.24 on liver disease and 90% precision. They were able to
increase that by 10-20 points on the F1 score by adding the CPSO on top
of the SVM model. **(10)**

**References**

**(1)** Adeoye, Abiodun O., et al. Utilizing Support Vector Machines for
Diabetes Mellitus Classification from Electronic Medical Records.
International Journal of Advanced Computer Science and Information
Technology (IJACSIT), vol. 11, no. 10, 2021, pp. 102-114.

**(2)** Fouodo, Cesaire, et al. Support Vector Machines for Survival
Analysis with R. R Journal, vol. 14, no. 2, 2022, pp. 92-107.

**(3)** Hu, Xiangfen, Wei Huang, and Qiang Wu. A New Support Vector
Machine Algorithm for Data Mining." Knowledge-Based Systems, vol. 112,
2016, pp. 118-128.

**(4)** Ismail, Gaber A., et al. An Approach Using Support Vector
Machines to Predict Hospital Readmission." Journal of Medical Systems,
vol. 44, no. 9, 2020, pp. 1-10.

**(5)** Xu, Fei, Lihong Li, and Zhihua Zhou. SVM Kernels for Data
Mining: A Comparative Study." Proceedings of the 2010 SIAM International
Conference on Data Mining (SDM), 2010, 585-596.

**(6)** Zhou, Xingyu, et al. Using Support Vector Machines for Deep
Mining of Electronic Medical Records in Order to Predict Prognosis of
Severe, Acute Myocardial Infarction. Frontiers in Cardiovascular
Medicine, vol. 10, 2023, p.918.

**(7)** Vieira, S.M., Mendonça, L. F., Farinha, G. J., & Sousa, J. M. C.
(2013). Modified binary PSO for feature selection using SVM applied to
mortality prediction of septic patients. *Applied Soft
Computing*, *13*(8), 3494--3504.
<https://doi.org/10.1016/j.asoc.2013.03.021>

**(8)** Yang, Zou, H., Wang, M., Zhang, Q., Li, S., & Liang, H. (2023).
Mortality prediction among ICU inpatients based on MIMIC-III database
results from the conditional medical generative adversarial
network. *Heliyon*, *9*(2), e13200--e13200.
<https://doi.org/10.1016/j.heliyon.2023.e13200>

**(9)** Chandrashekar, K., Setlur, A. S., Sabhapathi C, A., Raiker, S.
S., Singh, S., & Niranjan, V. (2023). Decision Support System and
Web-Application Using Supervised Machine Learning Algorithms for Easy
Cancer Classifications. *Cancer informatics*, *22*, 11769351221147244.
<https://doi.org/10.1177/11769351221147244>

**(10)** Mandakini Priyadarshani Behera, Archana Sarangi, Debahuti
Mishra, Shubhendu Kumar Sarangi, A Hybrid Machine Learning algorithm for
Heart and Liver Disease Prediction Using Modified Particle Swarm
Optimization with Support Vector Machine, Procedia Computer Science,
Volume 218, 2023,Pages 818-827,
<https://doi.org/10.1016/j.procs.2023.01.062>.

**Introduction**

Support Vector Machines (SVM) are an efficient way to mine data by
serving as a classification algorithm in Electronic Medical Records
(EMR). We find patterns in the data that might be hidden with other
statistical methods. SVMs will be used to make models that can use new
data to make accurate predictions. It is important to keep in mind,
though, that SVMs can be hard to train, especially on big datasets. SVMs
can also be responsive to how the SVM kernel and hyperparameters are
chosen. Once the SVM model has been trained, it can be used to guess
what will happen with new data. For example, a model could be used to
figure out how likely it is that a patient will get a certain illness or
what will happen to a patient who already has that disease. Before using
SVMs for data mining in EMRs, we need to prepare the data since the
noise and outliers should be taken out of the data. It is also important
to feature engineer the data, which will help make new features that may
be more useful for the SVM model.

SVMs can be used to get useful information from the data and to make
models that can improve the care of patients. SVMs can determine a model
to predict which patients might survive a severe illness in the
hospital. This is important for data mining in EMRs, where the data is
often complicated since SVMs can handle noise and errors well. This is
important for data mining in EMRs because the data may have errors or
missing data. This is important for data mining in EMRs because it would
be helpful to know how the models work, so we can have evidence to
support the results. Overall, SVMs can mine data in EMRs to create a new
SVM that can improve the care of patients by modeling who is at
increased risk of death. This can assist in predicting the probability
of those patients at risk for mortality in the Intensive Care Unit
(ICU).

## Methods

MIMIC-III is a , free database with information about the health of more
than 40,000 people who stayed in the critical care units of the Beth
Israel Deaconess Medical Center between 2001 and 2012. The information
has been stripped of all personal information. The database has
information like demographics, measurements of vital signs taken at the
bedside (about one data point per hour), lab test results, procedures,
medicines, caregiver notes, imaging reports, and deaths (including those
that happened after the patient was released from the hospital).

MIMIC helps with a wide range of analytical studies, including
statistics, improving clinical decision rules, and making electronic
tools. It is important for three reasons: researchers from anywhere in
the world can use it for free, it includes a very large and diverse
group of ICU patients, and it has very detailed information like vital
signs, lab results, and medications.

Under a data use agreement, MIMIC-III combines de-identified, complete
clinical data from patients who were admitted to the Beth Israel
Deaconess Medical Center in Boston, Massachusetts. This data is then
made available to researchers all over the world. Because the data are
public, clinical studies can be repeated and made better in ways that
would not be possible otherwise.

The MIMIC-III database was filled with information that was collected
during normal hospital care, so it didn't add any extra work for nurses
or get in the way of their work. Data was taken from a number of places,
including:

Critical care information tools and hospital electronic health record
databases have records from the past.

Death by the Social Security Administration The main file.

During the time when the data was collected, there were two different
critical care information systems: the Philips CareVue Clinical
Information System (types M2331A and M1215A; Philips Health-care,
Andover, MA) and the iMDsoft MetaVision ICU (iMDsoft, Needham, MA).

These tools were where clinical information like:

Physiological measures taken by a nurse and time-stamped (for example,
recording the heart rate, arterial blood pressure, or breathing rate
every hour); care providers' written notes on the patient's progress;
and medications and fluid balances given through an intravenous drip.

With the exception of data about fluid intake, which was very different
between the CareVue and MetaVision systems in how it was set up, data
was combined when the database tables were made. For data that couldn't
be combined, a suffix is added to show where the data came from. For
example, inputs for patients being monitored with the CareVue system are
stored in INPUTEVENTS_CV, while inputs for patients being monitored with
the Metavision system are stored in INPUTEVENTS_MV. From hospital and
lab health record systems, more information was gathered, including:

patient characteristics and deaths in the hospital.

Some examples of lab test results are hematology, chemistry, and
microbiology.

discharge summaries and reports of imaging tests and electrocardiograms.

Information about bills, such as International Classification of
Diseases, 9th Edition (ICD-9) codes, Diagnosis Related Group (DRG)
codes, and Current Procedural Terminology (CPT) codes.

The Social Security Administration's Death Master File was used to find
out when people died outside of hospitals.

Before the data was put into the MIMIC-III database, it was deidentified
using structured data cleaning and date shifting, as required by the
Health Insurance Portability and Accountability Act (HIPAA). For
structured data to be deidentified, all 18 of the identifying data
elements listed in HIPAA had to be taken out. This included areas like
the patient's name, phone number, address, and dates. In particular,
times were moved into the future by a random amount for each patient in
the same way so that intervals could be kept. This made stays happen
between the years 2100 and 2200. Date moving did not change the time of
day, the day of the week, or the season. To hide their real ages and
follow HIPAA rules, the dates of birth of patients older than 89 were
changed. In the database, these patients have ages of over 300 years.

Protected health information was taken out of free-text fields like
diagnostic reports and doctor's notes using a thoroughly tested
deidentification system based on extensive dictionary look-ups and
pattern-matching with regular expressions. As more information is
collected, this deidentification device keeps getting more parts.

Institutional Review Boards at the Beth Israel Deaconess Medical Center
in Boston, Massachusetts, and the Massachusetts Institute of Technology
in Cambridge, Massachusetts, gave their approval to the project.
Patients didn't have to give their consent because the project didn't
affect professional care and all protected health information was made
anonymous.

MIMIC-III is a set of 26 tables that make up a relational database.
Identifiers, which usually end in 'ID', are used to link tables
together. For example, SUBJECT_ID is used to identify a unique patient,
HADM_ID is used to identify a unique hospital admission, and ICUSTAY_ID
is used to identify a unique hospital entry to an intensive care unit.

In a set of "events" tables, things like notes, lab tests, and fluid
balance are kept track of. For example, the OUTPUTEVENTS table has all
the information about a patient's output, while the LABEVENTS table has
the results of a patient's lab tests.

Dictionary tables are those that start with "D\_" and give meanings for
identifiers. For example, each row of CHARTEVENTS has a single ITEMID
that stands for the idea being measured, but it doesn't have the name of
the measurement. By joining CHARTEVENTS and D_ITEMS on ITEMID, you can
find out what idea an ITEMID stands for.

When making the MIMIC data model, it was important to find a balance
between how easy it was to understand and how close it was to the real
world. So, the model is a reflection of the data sources it is based on.
The MIMIC database has been changed over time based on user comments.
When changes were done, care was taken not to make assumptions about the
underlying data. This means that MIMIC-III is a good representation of
the raw hospital data.

Five tables, called ADMISSIONS, PATIENTS, ICUSTAYS, SERVICES, and
TRANSFERS, are used to describe and keep track of patient stays. Five
more tables, D_CPT, D_ICD_DIAGNOSES, D_ICD_PROCEDURES, D_ITEMS, and
D_LABITEMS, are dictionaries that let you look up codes by their
meanings. The rest of the tables have information about patient care,
like measurements of the patient's body, notes from caregivers, and
payment information.

MIMIC-III is given as a set of comma-separated value (CSV) files and
tools to help import the data into database systems like PostreSQL,
MySQL, and MonetDB. Since the database has a lot of knowledge about how
to care for patients clinically, it needs to be treated with care and
respect.

<https://mimic.mit.edu/docs/iv/modules/icu/> is where we got the ICU
dataset,

** Patient demographics:**

o Age: Median 65.8 years (Q1--Q3: 52.8--77.8 years)

o Sex: 55.9% male

o In-hospital mortality: 11.5%

** Vital signs:**

o Heart rate: Median 98 beats per minute (Q1--Q3: 76--120 beats per

minute)

o Blood pressure: Median systolic blood pressure 134 mmHg (Q1--Q3:

116--154 mmHg); median diastolic blood pressure 78 mmHg (Q1--Q3:

66--90 mmHg)

o Respiratory rate: Median 20 breaths per minute (Q1--Q3: 16--24 breaths

per minute)

o Temperature: Median 36.8 °C (Q1--Q3: 36.5--37.1 °C)

o Oxygen saturation: Median 96% (Q1--Q3: 93--99%)

 **Laboratory values:**

o White blood cell count: Median 10.5 × 10\^9 cells/L (Q1--Q3: 7.5--14.5
×

10\^9 cells/L)

o Neutrophil count: Median 7.5 × 10\^9 cells/L (Q1--Q3: 5.4--11.2 ×
10\^9

cells/L)

o Lymphocyte count: Median 1.7 × 10\^9 cells/L (Q1--Q3: 1.0--2.5 × 10\^9

cells/L)

o Platelet count: Median 178 × 10\^9 cells/L (Q1--Q3: 125--240 × 10\^9

cells/L)

o Creatinine: Median 1.0 mg/dL (Q1--Q3: 0.8--1.3 mg/dL)

o Bilirubin: Median 0.8 mg/dL (Q1--Q3: 0.5--1.2 mg/dL)

o Lactate dehydrogenase: Median 250 U/L (Q1--Q3: 190--330 U/L)

## Analysis and Results

### Data and Visualization

```         
```

```         
```

### Statistical Modeling

### Conclusion

## References
